// Font Awesome 설정
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  // 일반 아이콘들
  faSearch,
  faBolt,
  faBook,
  faCog,
  faChartLine,
  faLink,
  faBullseye,
  faBrain,
  faLightbulb,
  faChartBar,
  faPlus,
  faFolder,
  faTrash,
  faUsers,
  faCheckCircle,
  faFileAlt,
  faDesktop,
  faClipboard,
  faRocket,
  faGem,
  faBalanceScale,
  faEdit,
  faFlask,
  faStar,
  faSpinner,
  faExclamationTriangle,
  faInfoCircle,
  faHome,
  faTachometerAlt,
  faCogs,
  faUsersCog,
  faChartPie,
  faDownload,
  faUpload,
  faShare,
  faSave,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faUser,
  faSignOutAlt,
  faBell,
  faEnvelope,
  faCalendar,
  faClock,
  faMapMarker,
  faPhone,
  faGlobe,
  faDatabase,
  faServer,
  faCloud,
  faShield,
  faKey,
  faWrench,
  faTools
} from '@fortawesome/free-solid-svg-icons';

// 라이브러리에 아이콘 추가
library.add(
  faSearch,
  faBolt,
  faBook,
  faCog,
  faChartLine,
  faLink,
  faBullseye,
  faBrain,
  faLightbulb,
  faChartBar,
  faPlus,
  faFolder,
  faTrash,
  faUsers,
  faCheckCircle,
  faFileAlt,
  faDesktop,
  faClipboard,
  faRocket,
  faGem,
  faBalanceScale,
  faEdit,
  faFlask,
  faStar,
  faSpinner,
  faExclamationTriangle,
  faInfoCircle,
  faHome,
  faTachometerAlt,
  faCogs,
  faUsersCog,
  faChartPie,
  faDownload,
  faUpload,
  faShare,
  faSave,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faUser,
  faSignOutAlt,
  faBell,
  faEnvelope,
  faCalendar,
  faClock,
  faMapMarker,
  faPhone,
  faGlobe,
  faDatabase,
  faServer,
  faCloud,
  faShield,
  faKey,
  faWrench,
  faTools
);

// 이모지 → Font Awesome 매핑
export const emojiToFontAwesome = {
  '🔍': 'search',
  '⚡': 'bolt',
  '📚': 'book',
  '⚙️': 'cog',
  '📈': 'chart-line',
  '🔗': 'link',
  '🎯': 'bullseye',
  '🧠': 'brain',
  '💡': 'lightbulb',
  '📊': 'chart-bar',
  '➕': 'plus',
  '+': 'plus',
  '📂': 'folder',
  '🗑️': 'trash',
  '👥': 'users',
  '✅': 'check-circle',
  '📄': 'file-alt',
  '💻': 'desktop',
  '📋': 'clipboard',
  '🚀': 'rocket',
  '💎': 'gem',
  '⚖️': 'balance-scale',
  '📝': 'edit',
  '🧪': 'flask',
  '⭐': 'star',
  '🔄': 'spinner',
  '⚠️': 'exclamation-triangle',
  'ℹ️': 'info-circle',
  '🏠': 'home',
  '📱': 'tachometer-alt',
  '🔧': 'wrench',
  '👤': 'user',
  '📤': 'upload'
};

export default emojiToFontAwesome;